# Generated by Django 4.1.7 on 2023-03-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('paragraph', models.TextField()),
                ('correct', models.CharField(max_length=2)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
