# Generated by Django 4.1.7 on 2023-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_questions_answer1_questions_answer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
