# Generated by Django 4.1.7 on 2023-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_questions_answer1_alter_questions_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='paragraph',
            field=models.TextField(null=True),
        ),
    ]
