# Generated by Django 4.1.7 on 2023-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_questions_image_alter_questions_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
