# Generated by Django 4.1.7 on 2023-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_questions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
