# Generated by Django 4.1.7 on 2023-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.IntegerField(null=True),
        ),
    ]
