# Generated by Django 4.1.7 on 2023-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_userprofile_math_score_userprofile_verbal_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='math_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verbal_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
