# Generated by Django 4.1.7 on 2023-03-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_userprofile_math_score_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numberoftest',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
